# -*- coding: utf-8 -*-
"""datachalenge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fZ0YK1gVlow6sFOgCVR485KbIt4MncLV
"""

import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.interpolate import BSpline
import seaborn as sns
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import silhouette_score
from sklearn_extra.cluster import KMedoids
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from tensorflow.keras.layers import Dense
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Function to download data from Google Drive shared link
def download_from_google_drive(url):
  """Downloads a file from a Google Drive shared link."""
  # Extract the file ID from the URL
  file_id = url.split('/')[-2]  # Get the part after 'd/' and before '/view'

  # Construct the download URL
  download_url = f"https://drive.google.com/uc?id={file_id}&export=download"

  return pd.read_csv(download_url)

# Download train_x
data_path = "https://drive.google.com/file/d/1PcMvAlIxJ2N9L47wtkOCtPB3lJwiv2CP/view?usp=sharing"
train_x = download_from_google_drive(data_path)

# Download train_y
data_path = "https://drive.google.com/file/d/1ScQWargY4OjGiRX1GltMXr8feQo8Zkph/view?usp=sharing"
train_y = download_from_google_drive(data_path)

# Process train_y (extract date and station, rename column)
if 'date' not in train_y.columns or 'station' not in train_y.columns:
    train_y[['date', 'station']] = train_y['index'].str.split('_', expand=True)
    train_y = train_y.drop(columns=['index'])

train_y = train_y.rename(columns={'y': 'nombre de validation'})
print(train_y)

train_merged = pd.merge(train_x, train_y, on=['date', 'station'], how='inner')
print(train_merged)

print(train_x)

train_merged['date'] = pd.to_datetime(train_merged['date'])

print(train_merged)

train_merged['month'] = train_merged['date'].dt.month
train_merged['day'] = train_merged['date'].dt.day

daily_average = train_merged.groupby(['station', 'month', 'day'])['nombre de validation'].mean().reset_index()
daily_average = daily_average.rename(columns={'nombre de validation': 'daily_average_validations'})

train_merged = pd.merge(train_merged, daily_average, on=['station', 'month', 'day'], how='left')

# train_merged = train_merged.drop(columns=['month', 'day'])

train_merged['date'] = pd.to_datetime(train_merged['date'])
train_merged = train_merged.sort_values(by=['station', 'date'])
grouped = train_merged.groupby('station')
stations = train_merged['station'].unique()
train_merged['nombre de validation'] = np.log1p(train_merged['nombre de validation'])

print(train_merged)

# Create the station mapping
station_mapping = {station: i for i, station in enumerate(train_merged['station'].unique())}

# Apply the mapping to train_merged
train_merged['station_num'] = train_merged['station'].map(station_mapping)

print(train_merged)

print(f"Taille de train_x : {train_x.shape}")
print(f"Taille de train_y : {train_y.shape}")
print(f"Taille de train_merged : {train_merged.shape}")

train_merged['date'] = pd.to_datetime(train_merged['date'])
train_merged = train_merged.sort_values(by=['station', 'date'])
grouped = train_merged.groupby('station')
stations = train_merged['station'].unique()

#import pandas as pd
from skfda.representation.basis import Fourier, BSpline
from skfda.representation.grid import FDataGrid
import matplotlib.pyplot as plt
import numpy as np

train_merged['date'] = pd.to_datetime(train_merged['date'])
train_merged = train_merged.sort_values(by=['station', 'date'])


grouped = train_merged.groupby('station')
stations = train_merged['station'].unique()

#fourier
fourier_basis = Fourier(n_basis=21, domain_range=(0, 365))


fd_fourier_list = []
for i, (station, group) in enumerate(grouped):
    y = group['nombre de validation'].values


    x = np.arange(len(group))


    fd = FDataGrid(data_matrix=y, grid_points=x)


    fd.basis = fourier_basis

    fd_fourier_list.append(fd)

# Define B-spline basis
bspline_basis = BSpline(n_basis=21, domain_range=(0, 365))


fd_bspline_list = []
for i, (station, group) in enumerate(grouped):
    y = group['nombre de validation'].values


    x = np.arange(len(group))


    fd = FDataGrid(data_matrix=y, grid_points=x)


    fd.basis = bspline_basis

    fd_bspline_list.append(fd)


for i in range(min(3, len(fd_fourier_list))):
    fig, axes = plt.subplots(1, 2, figsize=(10, 4))

    fd_fourier_list[i].plot(axes[0], label=f'Station {stations[i]} (Fourier)')
    fd_bspline_list[i].plot(axes[1], label=f'Station {stations[i]} (B-spline)')

    axes[0].set_title('Evolution with Fourier Basis')
    axes[1].set_title('Evolution with B-spline Basis')

    plt.show()

import matplotlib.pyplot as plt

station_index = 1

# Sélectionner les données de la station
station_data = train_merged[train_merged['station'] == stations[station_index]]

# Extraire les dates et les nombres de validations
dates = station_data['date']
validations = station_data['nombre de validation']

# Calculer les prédictions de Fourier
original_x = station_data['date'].dt.dayofyear.values
fourier_pred = fd_fourier_list[station_index].evaluate(original_x.reshape(-1, 1)).squeeze()

# Tracer l'évolution réelle et la courbe de Fourier
plt.figure(figsize=(8, 4))
plt.plot(dates, validations, label='Données réelles', color='blue')
plt.plot(dates, fourier_pred, label='Base de Fourier', color='red', linestyle='--')
plt.title(f"Évolution réelle et modélisée (Fourier) du nombre de validations pour la station {stations[station_index]}")
plt.xlabel('Date')
plt.ylabel('Nombre de validations')
plt.legend()
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt

station_index = 1

# Sélectionner les données de la station
station_data = train_merged[train_merged['station'] == stations[station_index]]

# Extraire les dates et les nombres de validations
dates = station_data['date']
validations = station_data['nombre de validation']

# Calculer les prédictions de Fourier et B-spline
original_x = station_data['date'].dt.dayofyear.values
fourier_pred = fd_fourier_list[station_index].evaluate(original_x.reshape(-1, 1)).squeeze()
bspline_pred = fd_bspline_list[station_index].evaluate(original_x.reshape(-1, 1)).squeeze()  # Calculer les prédictions B-spline

# Tracer l'évolution réelle, la courbe de Fourier et la courbe B-spline
plt.figure(figsize=(8, 4))
plt.plot(dates, validations, label='Données réelles', color='blue')
plt.plot(dates, bspline_pred, label='Base B-spline', color='green', linestyle='-.')  # Tracer la courbe B-spline
plt.title(f"Évolution  dans B-spline du nombre de validations pour la station {stations[station_index]}")
plt.xlabel('Date')
plt.ylabel('Nombre de validations')
plt.legend()
plt.grid(True)

import gdown

file_id = "1mYa7dqccu2Ha7g5dPvuJGwSWFN48GP1T"

url = f"https://drive.google.com/uc?id={file_id}"
output = "test_x.csv"
gdown.download(url, output, quiet=False)

# Now read the downloaded CSV file
test_x = pd.read_csv(output, header=0, sep=',')

# ... (previous code for creating station_mapping and applying it to train_x) ...

# Apply mapping to test_x
test_x['station_num'] = test_x['station'].map(station_mapping)

# Handle unknown stations (optional)
test_x['station_num'] = test_x['station'].map(station_mapping).fillna(-1).astype(int)

# ... (rest of your code) ...

test_x['date'] = pd.to_datetime(test_x['date'])

test_x['month'] = test_x['date'].dt.month
test_x['day'] = test_x['date'].dt.day

print(test_x)

daily_average_filtered = daily_average[daily_average['month'].between(1, 5)]



print(test_x)

test_stations = test_x['station'].unique()



train_merged['day_of_week'] = pd.to_datetime(train_merged['date']).dt.dayofweek + 1

train_merged['job_day_interaction'] = train_merged['job'] * train_merged['day_of_week']

test_x['day_of_week'] = test_x['date'].dt.dayofweek + 1
test_x['job_day_interaction'] = test_x['job'] * test_x['day_of_week']

# Filter daily_average to include only months 1 to 5
daily_average_filtered = daily_average[daily_average['month'].between(1, 6)]

# Merge daily_average_filtered with test_x
test_x = pd.merge(test_x, daily_average_filtered[['station', 'month', 'day', 'daily_average_validations']],
                  on=['station', 'month', 'day'], how='left')

# Handle missing values if any (optional)
test_x['daily_average_validations'].fillna(test_x['daily_average_validations'].mean(), inplace=True)

print(test_x)

import numpy as np
from skfda import FDataGrid

fourier_coeffs = [fd.data_matrix.flatten() for fd in fd_fourier_list]

bspline_coeffs = [fd.data_matrix.flatten() for fd in fd_bspline_list]
max_len = max(len(arr) for arr in fourier_coeffs)
fourier_coeffs_padded = [np.pad(arr, (0, max_len - len(arr)), 'constant') for arr in fourier_coeffs]
bspline_coeffs_padded = [np.pad(arr, (0, max_len - len(arr)), 'constant') for arr in bspline_coeffs]

X_fourier = np.array(fourier_coeffs_padded)
X_bspline = np.array(bspline_coeffs_padded)

fourier_cols = [f'fourier_coeff_{i}' for i in range(fourier_basis.n_basis)]
bspline_cols = [f'bspline_coeff_{i}' for i in range(bspline_basis.n_basis)]
for i, station in enumerate(stations):
    train_merged.loc[train_merged['station'] == station, fourier_cols] = fourier_coeffs[i][0]

    train_merged.loc[train_merged['station'] == station, bspline_cols] = bspline_coeffs[i][0]

print(train_merged)

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X = train_merged[['job','ferie','vacances','month']]
y_fourier = train_merged[[f'fourier_coeff_{i}' for i in range(fourier_basis.n_basis)]]
y_bspline = train_merged[[f'bspline_coeff_{i}' for i in range(bspline_basis.n_basis)]]

X_train, X_val, y_fourier_train, y_fourier_val = train_test_split(X, y_fourier, test_size=0.2, random_state=42)
X_train, X_val, y_bspline_train, y_bspline_val = train_test_split(X, y_bspline, test_size=0.2, random_state=42)

fourier_model = LinearRegression()
fourier_model.fit(X_train, y_fourier_train)

bspline_model = LinearRegression()
bspline_model.fit(X_train, y_bspline_train)

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import make_pipeline


X = train_merged[['job','ferie','vacances']]
y_fourier = train_merged[[f'fourier_coeff_{i}' for i in range(fourier_basis.n_basis)]]
y_bspline = train_merged[[f'bspline_coeff_{i}' for i in range(bspline_basis.n_basis)]]

X_train, X_val, y_fourier_train, y_fourier_val = train_test_split(X, y_fourier, test_size=0.2, random_state=42)
X_train, X_val, y_bspline_train, y_bspline_val = train_test_split(X, y_bspline, test_size=0.2, random_state=42)

fourier_model = make_pipeline(PolynomialFeatures(degree=2), Ridge(alpha=1.0))
bspline_model = make_pipeline(PolynomialFeatures(degree=2), Ridge(alpha=1.0))

# model
fourier_model.fit(X_train, y_fourier_train)
#bspline_model.fit(X_train, y_bspline_train)

param_grid = {
    'polynomialfeatures__degree': [1, 2, 3],
    'ridge__alpha': [0.1, 1.0, 10.0]
}

grid_search = GridSearchCV(fourier_model, param_grid, cv=5, scoring='neg_mean_squared_error')
grid_search.fit(X_train, y_fourier_train)

best_fourier_model = grid_search.best_estimator_

import pandas as pd
from sklearn.linear_model import LinearRegression



test_data = test_x[['job', 'ferie', 'vacances','month']]

test_data = test_data.astype(int)

predicted_fourier_coeffs = best_fourier_model.predict(test_data)

#predicted_bspline_coeffs = best_bspline_model.predict(test_data)



from sklearn.ensemble import BaggingRegressor
from sklearn.model_selection import train_test_split



#  Bagging Regressor models for Fourier coefficients
fourier_bagging_models = []
for i in range(y_fourier_train.shape[1]):
    bagging_model = BaggingRegressor(random_state=42)
    bagging_model.fit(X_train, y_fourier_train.iloc[:, i])
    fourier_bagging_models.append(bagging_model)

# Create Bagging Regressor models for B-spline coefficients
#bspline_bagging_models = []
#for i in range(y_bspline_train.shape[1]):
    #bagging_model = BaggingRegressor(random_state=42)
    #bagging_model.fit(X_train, y_bspline_train.iloc[:, i])
    #bspline_bagging_models.append(bagging_model)

# Predict Fourier coefficients on test_x
predicted_fourier_coeffs = [model.predict(test_x[['job', 'ferie', 'vacances','month']]) for model in fourier_bagging_models]
#predicted_fourier_coeffs = np.array(predicted_fourier_coeffs).T

# Predict B-spline coefficients on test_x
#predicted_fourier_coeffs = [model.predict(test_x[['job', 'ferie', 'vacances', 'month']])

from skfda.representation.basis import FourierBasis, FDataBasis
import numpy as np

#1
fourier_basis = Fourier(n_basis=21, domain_range=(0, 365))
print(predicted_fourier_coeffs.shape)


if predicted_fourier_coeffs.shape[1] > fourier_basis.n_basis:
    predicted_fourier_coeffs = predicted_fourier_coeffs[:, :fourier_basis.n_basis]


fd_reconstructed = FDataBasis(basis=fourier_basis, coefficients=predicted_fourier_coeffs)


days = np.linspace(0, 151, 152)  #  1er janvier au 31 mai
reconstructed_values = fd_reconstructed.evaluate(days)


print(reconstructed_values.shape)

from skfda.representation.basis import FourierBasis, FDataBasis
import numpy as np
#Bagging tree 1
fourier_basis = FourierBasis(n_basis=21, domain_range=(0, 365))


predicted_fourier_coeffs = np.array(predicted_fourier_coeffs)


predicted_fourier_coeffs = predicted_fourier_coeffs.T


print(predicted_fourier_coeffs.shape)

if predicted_fourier_coeffs.shape[1] > fourier_basis.n_basis:
    predicted_fourier_coeffs = predicted_fourier_coeffs[:, :fourier_basis.n_basis]

fd_reconstructed = FDataBasis(basis=fourier_basis, coefficients=predicted_fourier_coeffs)


days = np.linspace(0, 151, 152)   #1er janvier au 31 mai
reconstructed_values = fd_reconstructed.evaluate(days)


print(reconstructed_values.shape)

from skfda.representation.basis import FourierBasis, FDataBasis
import numpy as np

#2
fd_reconstructed = FDataBasis(fourier_basis, predicted_fourier_coeffs)

days = np.linspace(0, 151, 152)
reconstructed_values = fd_reconstructed.evaluate(days)


day_columns = [f'day_{i}' for i in range(len(days))]


reconstructed_values_transposed = reconstructed_values.reshape(len(test_x), len(days))


reconstructed_df = pd.DataFrame(reconstructed_values_transposed, columns=day_columns, index=test_x.index)


test_x = pd.concat([test_x, reconstructed_df], axis=1)

print(test_x.head())

print(test_x)

#3
fd_reconstructed = FDataBasis(basis=fourier_basis, coefficients=predicted_fourier_coeffs)


days = np.linspace(0, 151, 152)
reconstructed_values = fd_reconstructed.evaluate(days)


stations = test_x['station'].unique()
station_mapping = {station: i for i, station in enumerate(stations)}


def get_prediction(row):
    station_idx = station_mapping[row['station']]
    day_idx = row['day'] - 1
    return reconstructed_values[station_idx, day_idx]

test_x['nombre de validation'] = test_x.apply(get_prediction, axis=1)

#4
def get_prediction(row):
    station_idx = station_mapping[row['station']]
    day_idx = row['day'] - 1
    prediction = reconstructed_values[station_idx, day_idx]
    return prediction.item() if isinstance(prediction, np.ndarray) else prediction

test_x['nombre de validation'] = test_x.apply(get_prediction, axis=1)

print(test_x)

test_x['nombre de validation'] = np.expm1(test_x['nombre de validation'])#5

print(test_x)

test_x= test_x[['index', 'nombre de validation']]#6
print(test_x)

min_validations = test_x['nombre de validation'].min()
max_validations = test_x['nombre de validation'].max()

print(f"Minimum nombre de validation: {min_validations}")
print(f"Maximum nombre de validation: {max_validations}")

test_x['nombre de validation'] = test_x['nombre de validation'].clip(lower=0)#7

print(test_x)

from google.colab import files

# Save the DataFrame to a CSV file
test_x.to_csv('submission.csv', index=False)

# Download the file
files.download('submission.csv')

from IPython.display import FileLink
test_x.to_csv('submission.csv', index=False)
FileLink('submission.csv')